### ISSUE TITLE
Planned support for Airline?

### ISSUE THREAD

**Issue by NeckBeardPrince** [catppuccin/vim#10]

**Comment by nullchilly** [comment]
[catppuccin/nvim](https://github.com/catppuccin/nvim) supports [airline](https://github.com/catppuccin/nvim/blob/main/autoload/airline/themes/catppuccin.vim) for vanilla vim if you can affort the lua dependency. Otherwise you wait for this repo's integration.

**Comment by M3nny** [comment]
Sorry, I am very busy right now with the university, so I can't promise anything, you can always make a pull request if you want.
