### ISSUE TITLE
The theme color is displayed abnormally

### ISSUE THREAD

**Issue by livrth** [catppuccin/vim#12]
I configured it according to the instructions in the README, and the terminal I use is alacirtty. The display is as follows, the colors look very strange, as well as the color of lightline.

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/45538642/206852620-0d6a998b-9a97-4b35-b677-6a00ec0391d7.png">

What am I doing wrong? Thanks.

**Comment by M3nny** [comment]
Do other color themes work?

**Comment by livrth** [comment]
> Do other color themes work?

This may be a problem of alacrity, I switched to other terminal emulators and it workes, thank you!
