### ISSUE TITLE
Theme doesn't look right without `termguicolors`

### ISSUE THREAD

**Issue by abrendtro** [catppuccin/vim#15]
I would like Vim/Neovim to use my terminal's color palette. For some reason, though, disabling `termguicolors` breaks the theme:

![image](https://user-images.githubusercontent.com/122829274/221385875-2ce21a1c-05a2-4723-aef0-10cf3f0f17ed.png)

For reference, here's what it's supposed to look like:

![image](https://user-images.githubusercontent.com/122829274/221385902-7e833689-aa8f-4ac6-9746-77204586b9f8.png)

**Comment by maxjcohen** [comment]
Hi, this theme requires `termguicolors`, as mentioned in the [README](https://github.com/catppuccin/vim#usage). See also #1 .

**Comment by extremepayne** [comment]
If anyone else wants catppuccin (or any other traditional terminal theme) to work without `set termguicolors`, try [this theme](https://jeffkreeftmeijer.com/vim-16-color/) instead.
