### ISSUE TITLE
Line number in formatting error bar isn't visible

### ISSUE THREAD

**Issue by fozziethebeat** [catppuccin/vim#16]
I'm using vim with the `prettier/vim-prettier` plugin.  Anytime I save a file, it tries to run prettier and reformat the file.

I've discovered that with all the catppuccin themes, the error bar that shows a line number with some syntax error doesn't show the line number information correctly.  Everything else is correct but this one small section isn't right.

I normally run vim within tmux using szh and iterminal 2 on OSX.  Ive confirmed this problem exists both in and not in tmux and in zsh along with bash.  I tried Terminal.app as well but my config there is off so the theme looks like a mess from the start so I'm not sure if this is an iterm or terminal issue.

Attached is a screenshot of what the error looks like.

Any suggestions on what setting I need to change to get this working right?

<img width="1115" alt="Screenshot 2023-05-18 at 8 20 04 AM" src="https://github.com/catppuccin/vim/assets/398211/bd2b32cd-31ea-48ec-a811-59fdb430ca79">

**Comment by M3nny** [comment]
Hi fozzie,
I've never used prettier, probably to display the line number information it uses the same color as the foreground in the background, resulting in no visible text.
Perhaps it is possible, with a small modification, to customize the colors of the prettier plugin and correct this problem.
