### ISSUE TITLE
I don't seem able to override the Pmenu background color.

### ISSUE THREAD

**Issue by bitwombat** [catppuccin/vim#17]
The pop-up diagnostics screen has a background too close to Catppuccin's background, so I'd like to make it lighter.

My config for neovim 0.9.0 and catpuccin ad63055 is:

  ```
{
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    integrations = {
      mason = true,
    },
    custom_highlights = function(colors)
      return {
        Pmenu = { bg = "#808000" },
      }
    end
  },
```
But it has no effect, and the setting doesn't even take:

![image](https://github.com/catppuccin/vim/assets/3937658/6c9a6c31-2e2b-40c5-9041-8fd69763a04b)

I also get no effect with an `:hi Pmenu guibg=#808000`  either.

The weird thing is that the `:hi` command does have an effect if I use the built-in themes (eg. `blue` or `dalek`).

User error?

**Comment by M3nny** [comment]
Hi bitwombat,
it seems like that you are not using this port from your first line of configuration, you may want to try to use the [neovim](https://github.com/catppuccin/nvim) port instead

**Comment by bitwombat** [comment]
?? First line of config shown above is `"catppuccin/nvim",`

**Comment by cideM** [comment]
This is the `/vim` repository though

**Comment by nullchilly** [comment]
Dev of [catppuccin/nvim](https://github.com/catppuccin/nvim) here, you reported in the wrong repo.

Anyway, plugin config should be inside `opts = {}`

```lua
diff --git a/wrong.lua b/true.lua
index 6a84a2c..98ca270 100644
--- a/wrong.lua
+++ b/true.lua
@@ -5,11 +5,13 @@
                integrations = {
                        mason = true,
                },
-               custom_highlights = function(colors)
-                       return {
-                               Pmenu = { guibg = "#808000" },
-                       }
-               end
+               opts = {
+                       custom_highlights = function(colors)
+                               return {
+                                       Pmenu = { guibg = "#808000" },
+                               }
+                       end
+               },
        },
```

**Comment by bitwombat** [comment]
> you reported in the wrong repo.

Ooooo!  Der. Thanks. And thanks for developing/supporting catppuccin/nvim.

The above still didn't "take". I'll go report in the right repo.
