### ISSUE TITLE
Trouble with download branch from vimplug

### ISSUE THREAD

**Issue by xamaterasux** [catppuccin/vim#20]
Hello,

When I try to install this theme in vim with vimplug I get this error:
```
- Finishing ... Done!                                                                                               |~                                                                                                                  
x vim:                                                                                                              |~                                                                                                                  
    fatal: invalid reference: master 
```

Checking your repository, the main branch is called `main`, not `master`.. maybe that's the problem.

Regards!

**Comment by isabelroses** [comment]
If you belive it is caused by the branch issue try `Plug 'catppuccin/vim', { 'branch': 'main' }`.

**Comment by xamaterasux** [comment]
I tried to update vimplug (:PlugUpgrade) and it made it work, so here's other workaround also.

Thank you for your quick reply:)
