### ISSUE TITLE
Unprintable characters blend in

### ISSUE THREAD

**Issue by L1Q** [catppuccin/vim#5]
With this theme enabled, unprintable characters blend in with the regular ones.
You can test this by setting ``listchars``:
```
set listchars=tab:»»,trail:·,nbsp:~
```
[sonokai](https://github.com/sainnhe/sonokai) (atlantis):
![image](https://user-images.githubusercontent.com/6942070/189726996-6992d99c-5e46-4fed-84e1-cf3f3ceee850.png)
catppuccin_macchiato:
![image](https://user-images.githubusercontent.com/6942070/189727162-af56a17e-a688-4fea-937e-2c3776fd259b.png)

**Comment by M3nny** [comment]
This should work

**Comment by L1Q** [comment]
An improvement for sure!
![image](https://user-images.githubusercontent.com/6942070/189866744-d54b4084-2a36-401a-a25d-fe92aba0a35d.png)

**Comment by M3nny** [comment]
I didn't want to deviate too much from the original theme, however if you want a lighter color, you can edit the **guifg** field in the **SpecialKey** highlight
