### ISSUE TITLE
Highlight groups with guifg=#ffffff unreadable in latte theme

### ISSUE THREAD

**Issue by bartlibert** [catppuccin/vim#6]
There are quite some highlight groups that have guifg=#ffffff (i.e. white). These are practically unreadable in the latte theme, due to the light background.

I have, for now, modified my vimrc to link all these groups to other groups, but a proper fix is desirable (also because my 'quick links' might not adhere to the guidelines or other editors).

```
    exec 'highlight! link Delimiter Special'
    exec 'highlight! link Tag Special'
    exec 'highlight! link SpecialChar Special'
    exec 'highlight! link Precondit Comment'
    exec 'highlight! link SpecialComment Comment'
    exec 'highlight! link Exception Error'
    exec 'highlight! link StatusLineTerm StatusLine'
    exec 'highlight! link StatusLineTermNC StatusLineNC'
    exec 'highlight! link Terminal Normal'
    exec 'highlight! link Ignore Comment'
    exec 'highlight! link Define Label'
    exec 'highlight! link Macro Label'
    exec 'highlight! link debugPC DiffText'
    exec 'highlight! link debugBreakpoint DiffDelete'
    exec 'highlight Underlined guifg=' s:GetColorFromHl('Normal', 'fg', 'gui') 'ctermfg=' s:GetColorFromHl('Normal', 'fg', 'cterm')
```

The last line uses some custom functions I have written,  but essentially means: "Underlined" is "Normal" but with underlines :smile:

**Comment by M3nny** [comment]
See if it works, some of the links do not follow the original theme so I have changed them, however I have kept some of those where there are no specific guidelines
