### ISSUE TITLE
Colors doesn't look right in nvim-cmp completion dialogs

### ISSUE THREAD

**Issue by ravener** [catppuccin/vim#7]
This is how it looks:

![Screenshot_20221002_215617](https://user-images.githubusercontent.com/31079629/193467733-b19816cd-c031-4914-86e7-bca934e4a7be.jpg)

Other colorschemes seems to look fine.

**Comment by nekowinston** [comment]
I'm guessing you're using neovim? Please check out https://github.com/catppuccin/nvim

**Comment by ravener** [comment]
Actually nevermind, this got fixed after I did `set termguicolors` BEFORE setting the colorscheme.

**Comment by M3nny** [comment]
Well this was fast

**Comment by ravener** [comment]
@nekowinston Thanks I'll check out the nvim plugin. I was a vimscript purist and was scared to aproach the lua ecosystem so I got this plugin, but I was recently playing with lua so I'll take a look.
