### ISSUE TITLE
Latte theme sets background to dark

### ISSUE THREAD

**Issue by bartlibert** [catppuccin/vim#8]
The latte theme, which has a light background, sets the `background` value to `dark` instead of `light`. This has some impact on, for example, the colors in Termdebug.

https://github.com/catppuccin/vim/blob/c9bbe18d3f22351c99c98eb53339ca0b2a1a18b5/colors/catppuccin_latte.vim#L3

**Comment by nekowinston** [comment]
Good catch, thanks!
