### ISSUE TITLE
Why set cursorline option in colorscheme

### ISSUE THREAD

**Issue by pbnj** [catppuccin/vim#9]
Thank you for a pleasant colorscheme.

I am wondering why a colorscheme sets options like `cursorline`?
Shouldn't it be up to users to enable or disable this option?

In my vimrc, I explicitly disable it and was surprised that it got enabled after installing the theme. `:verbose set cursorline?` revealed it was done by the colorscheme.

I can submit a PR to fix this, but wanted to inquire the maintainer(s)/contributor(s)/community opinions.

**Comment by M3nny** [comment]
I didn't see the theme as a bunch of colors, instead I wanted it to custumize other aspects of vim as well, so I included cursorline in the theme, I'll leave this issue open for now and see what others think.

**Comment by nullchilly** [comment]
No, you shouldn't set any option by default

If anything, `set termguicolors` should be the only thing you force on user
